# Generated by Django 6.0.2 on 2026-02-07 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('revision', 'Revision Needed'), ('practice', 'Additional Practice'), ('next_lesson', 'Ready for Next Lesson'), ('mastery', 'Concept Mastered'), ('simplified', 'Simplified Explanation')], max_length=20)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculumcapsule')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
                ('suggested_capsules', models.ManyToManyField(blank=True, related_name='recommended_for', to='api.curriculumcapsule')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('simulation_type', models.CharField(choices=[('math_visualization', 'Math Visualization'), ('science_experiment', 'Science Experiment'), ('interactive_diagram', 'Interactive Diagram'), ('step_by_step', 'Step by Step Guide')], max_length=30)),
                ('config', models.JSONField(default=dict, help_text='Simulation configuration and parameters')),
                ('instructions', models.TextField(blank=True)),
                ('hints', models.JSONField(default=list, help_text='AI-generated hints for the simulation')),
                ('learning_objectives', models.JSONField(default=list)),
                ('difficulty_level', models.CharField(default='intermediate', max_length=20)),
                ('estimated_time', models.IntegerField(default=10, help_text='Estimated time in minutes')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.grade')),
                ('related_capsule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='api.curriculumcapsule')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='api.subject')),
            ],
            options={
                'ordering': ['subject', 'grade', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SimulationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('interaction_data', models.JSONField(default=dict, help_text='Recorded user interactions')),
                ('hints_used', models.IntegerField(default=0)),
                ('completed_successfully', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_interactions', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.learningsimulation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerDifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('average_score', models.FloatField(default=0.0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('consecutive_passes', models.IntegerField(default=0)),
                ('consecutive_fails', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_levels', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
            options={
                'unique_together': {('learner', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='RevisionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_count', models.IntegerField(default=0)),
                ('last_revision', models.DateTimeField(auto_now=True)),
                ('improvement_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculumcapsule')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_activities', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
            ],
            options={
                'unique_together': {('learner', 'capsule')},
            },
        ),
    ]
