# Generated by Django 6.0.2 on 2026-02-10 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learningrecommendation_learningsimulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('introduction', models.TextField(blank=True, help_text='AI-generated introduction')),
                ('learning_objectives', models.JSONField(default=list, help_text='Extracted learning objectives')),
                ('key_concepts', models.JSONField(default=list, help_text='Main concepts covered')),
                ('estimated_duration', models.IntegerField(default=30, help_text='Estimated time in minutes')),
                ('difficulty_level', models.CharField(default='intermediate', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('generation_params', models.JSONField(default=dict, help_text='Parameters used for generation')),
                ('quality_score', models.FloatField(default=0.0, help_text='AI confidence score')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_capsule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_generated_lesson', to='api.curriculumcapsule')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('introduction', 'Introduction'), ('explanation', 'Explanation'), ('example', 'Example'), ('practice', 'Practice Activity'), ('real_world', 'Real World Application'), ('summary', 'Summary'), ('assessment', 'Quick Assessment')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Formatted section content')),
                ('order', models.IntegerField(default=0)),
                ('has_interactive_elements', models.BooleanField(default=False)),
                ('interactive_data', models.JSONField(blank=True, default=dict, help_text='Interactive exercises, diagrams, or activities')),
                ('embedded_questions', models.JSONField(blank=True, default=list, help_text='Questions to check understanding')),
                ('hints', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.generatedlesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('fill_blank', 'Fill in the Blank'), ('matching', 'Matching')], default='multiple_choice', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('options', models.JSONField(default=list, help_text='Answer options')),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation')),
                ('hints', models.JSONField(blank=True, default=list)),
                ('bloom_taxonomy_level', models.CharField(blank=True, help_text="Bloom's taxonomy classification", max_length=50)),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='api.generatedlesson')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_questions', to='api.lessonsection')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TextbookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('chapter_number', models.CharField(blank=True, max_length=20)),
                ('raw_content', models.TextField(help_text='Raw textbook content to be processed')),
                ('source_book', models.CharField(blank=True, help_text='Source textbook name', max_length=200)),
                ('page_numbers', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('generated', 'Generated'), ('published', 'Published'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_chapters', to='api.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_chapters', to='api.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'grade', 'chapter_number'],
            },
        ),
        migrations.AddField(
            model_name='generatedlesson',
            name='source_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_lessons', to='api.textbookchapter'),
        ),
    ]
