# Generated by Django 6.0.2 on 2026-02-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generatedlesson_lessonsection_generatedquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookchapter',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF file to extract content from', null=True, upload_to='textbook_pdfs/'),
        ),
        migrations.AlterField(
            model_name='textbookchapter',
            name='raw_content',
            field=models.TextField(blank=True, help_text='Raw textbook content to be processed'),
        ),
    ]
